In [1]:
import numpy as np

# 1 逻辑运算

In [2]:
score = np.random.randint(40,100,(10,5))

In [3]:
score

array([[69, 50, 87, 60, 67],
       [85, 85, 95, 91, 72],
       [67, 67, 56, 79, 76],
       [42, 55, 41, 86, 97],
       [93, 74, 71, 51, 45],
       [53, 65, 46, 47, 76],
       [94, 45, 94, 92, 93],
       [76, 76, 73, 50, 73],
       [86, 92, 48, 93, 46],
       [72, 92, 67, 40, 51]])

In [4]:
test_score = score[6:,0:5]

In [5]:
test_score

array([[94, 45, 94, 92, 93],
       [76, 76, 73, 50, 73],
       [86, 92, 48, 93, 46],
       [72, 92, 67, 40, 51]])

In [6]:
test_score>60

array([[ True, False,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False, False]])

In [7]:
test_score[test_score < 60] = 0

In [8]:
test_score

array([[94,  0, 94, 92, 93],
       [76, 76, 73,  0, 73],
       [86, 92,  0, 93,  0],
       [72, 92, 67,  0,  0]])

# 2 通用判断函数

In [9]:
np.all(score[0:2,:]>60)

False

In [10]:
score

array([[69, 50, 87, 60, 67],
       [85, 85, 95, 91, 72],
       [67, 67, 56, 79, 76],
       [42, 55, 41, 86, 97],
       [93, 74, 71, 51, 45],
       [53, 65, 46, 47, 76],
       [94,  0, 94, 92, 93],
       [76, 76, 73,  0, 73],
       [86, 92,  0, 93,  0],
       [72, 92, 67,  0,  0]])

In [11]:
np.any(score[0:2,:]>90)

True

In [12]:
score

array([[69, 50, 87, 60, 67],
       [85, 85, 95, 91, 72],
       [67, 67, 56, 79, 76],
       [42, 55, 41, 86, 97],
       [93, 74, 71, 51, 45],
       [53, 65, 46, 47, 76],
       [94,  0, 94, 92, 93],
       [76, 76, 73,  0, 73],
       [86, 92,  0, 93,  0],
       [72, 92, 67,  0,  0]])

In [13]:
# 3 np.where（三元运算符）

In [14]:
temp = score[:4,:4]

In [15]:
temp

array([[69, 50, 87, 60],
       [85, 85, 95, 91],
       [67, 67, 56, 79],
       [42, 55, 41, 86]])

In [16]:
np.where(temp > 60, 1, 0)

array([[1, 0, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 1]])

In [17]:
np.where(np.logical_and(temp>60,temp < 90),1,0)

array([[1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1]])

In [18]:
np.where(np.logical_or(temp<60,temp>90),1,0)

array([[0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 1, 1, 0]])

# 4 统计计算

In [19]:
temp = score[:4,:]

In [20]:
temp

array([[69, 50, 87, 60, 67],
       [85, 85, 95, 91, 72],
       [67, 67, 56, 79, 76],
       [42, 55, 41, 86, 97]])

In [21]:
np.max(temp)

97

In [22]:
np.mean(temp)

71.35

In [23]:
np.max(temp,axis=0)

array([85, 85, 95, 91, 97])

In [24]:
np.max(temp,axis=1)

array([87, 95, 79, 97])

In [25]:
np.argmax(temp)

19

In [26]:
np.argmax(temp,axis=0)

array([1, 1, 1, 1, 3], dtype=int64)

In [28]:
np.argmin(temp,axis=0)

array([3, 0, 3, 0, 0], dtype=int64)

# 5 数组间的运算

In [30]:
a = np.array([[1,2,3],[3,4,5]])

In [31]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [32]:
a +3

array([[4, 5, 6],
       [6, 7, 8]])

In [33]:
a / 2

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])

In [34]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [35]:
arr1 = np.array([[1,2,3,2,1,4],[5,6,1,2,3,1]])
arr2 = np.array([[1],[3]])

In [36]:
arr1.shape

(2, 6)

In [37]:
arr2.shape

(2, 1)

In [38]:
arr1+arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 6 矩阵的运算

In [39]:
a = np.array([[80,86],
              [82,80],
              [85,78],
              [90,90],
              [86,82],
              [78,80],
              [92,94]])

In [40]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [78, 80],
       [92, 94]])

In [43]:
b = np.array([[0.7],[0.3]])

In [44]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [78.6],
       [92.6]])

In [45]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [78.6],
       [92.6]])

In [47]:
c = 10

In [48]:
np.dot(c,a) # ·

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [780, 800],
       [920, 940]])

In [49]:
np.matmul(c,a) # ×

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)