# 1 Series

# 1.1 Series的创建

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.Series(np.arange(9))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int32

In [4]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
pd.Series([1.2,2.3,4.5,5.0],index=[1,2,3,4])

1    1.2
2    2.3
3    4.5
4    5.0
dtype: float64

In [6]:
color_count = pd.Series({"red":10,"green":20,"blue":30})

In [7]:
color_count

red      10
green    20
blue     30
dtype: int64

## Series的属性

In [8]:
color_count.index

Index(['red', 'green', 'blue'], dtype='object')

In [9]:
color_count.values

array([10, 20, 30], dtype=int64)

In [10]:
color_count[0]

10

In [11]:
color_count[1]

20

# DataFrame
## DataFrame创建

In [12]:
pd.DataFrame(np.random.randn(2,3))

0         1         2
0 -0.278129  0.367829  1.590343
1  0.094557  0.491571 -1.280931

In [13]:
score = np.random.randint(40,100,(10,5))

In [14]:
score

array([[61, 80, 87, 53, 42],
       [56, 80, 62, 84, 74],
       [78, 44, 66, 71, 67],
       [77, 47, 41, 89, 80],
       [42, 62, 96, 63, 63],
       [70, 54, 67, 56, 48],
       [44, 62, 49, 45, 91],
       [58, 96, 92, 46, 89],
       [97, 95, 48, 42, 92],
       [53, 42, 76, 82, 61]])

In [15]:
score_df = pd.DataFrame(score)

In [16]:
score_df

0   1   2   3   4
0  61  80  87  53  42
1  56  80  62  84  74
2  78  44  66  71  67
3  77  47  41  89  80
4  42  62  96  63  63
5  70  54  67  56  48
6  44  62  49  45  91
7  58  96  92  46  89
8  97  95  48  42  92
9  53  42  76  82  61

In [17]:
subjects = ["语文","数学","英语","政治","体育"]

stu = ["stu" +str(i) for i in range(score_df.shape[0])]

data = pd.DataFrame(score,columns=subjects,index=stu)

In [18]:
stu

['stu0',
 'stu1',
 'stu2',
 'stu3',
 'stu4',
 'stu5',
 'stu6',
 'stu7',
 'stu8',
 'stu9']

In [19]:
data

语文  数学  英语  政治  体育
stu0  61  80  87  53  42
stu1  56  80  62  84  74
stu2  78  44  66  71  67
stu3  77  47  41  89  80
stu4  42  62  96  63  63
stu5  70  54  67  56  48
stu6  44  62  49  45  91
stu7  58  96  92  46  89
stu8  97  95  48  42  92
stu9  53  42  76  82  61

In [20]:
## DataFrame的属性

In [21]:
data.shape

(10, 5)

In [22]:
data.index

Index(['stu0', 'stu1', 'stu2', 'stu3', 'stu4', 'stu5', 'stu6', 'stu7', 'stu8',
       'stu9'],
      dtype='object')

In [23]:
data.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [24]:
data.values

array([[61, 80, 87, 53, 42],
       [56, 80, 62, 84, 74],
       [78, 44, 66, 71, 67],
       [77, 47, 41, 89, 80],
       [42, 62, 96, 63, 63],
       [70, 54, 67, 56, 48],
       [44, 62, 49, 45, 91],
       [58, 96, 92, 46, 89],
       [97, 95, 48, 42, 92],
       [53, 42, 76, 82, 61]])

In [25]:
data.T

stu0  stu1  stu2  stu3  stu4  stu5  stu6  stu7  stu8  stu9
语文    61    56    78    77    42    70    44    58    97    53
数学    80    80    44    47    62    54    62    96    95    42
英语    87    62    66    41    96    67    49    92    48    76
政治    53    84    71    89    63    56    45    46    42    82
体育    42    74    67    80    63    48    91    89    92    61

In [26]:
data.head()

语文  数学  英语  政治  体育
stu0  61  80  87  53  42
stu1  56  80  62  84  74
stu2  78  44  66  71  67
stu3  77  47  41  89  80
stu4  42  62  96  63  63

In [27]:
data.head(3)

语文  数学  英语  政治  体育
stu0  61  80  87  53  42
stu1  56  80  62  84  74
stu2  78  44  66  71  67

In [28]:
data.tail()

语文  数学  英语  政治  体育
stu5  70  54  67  56  48
stu6  44  62  49  45  91
stu7  58  96  92  46  89
stu8  97  95  48  42  92
stu9  53  42  76  82  61

In [29]:
data.tail(2)

语文  数学  英语  政治  体育
stu8  97  95  48  42  92
stu9  53  42  76  82  61

## 2.3 DataFrame索引值的设置

In [30]:
stu = ["stu_"+str(i) for i in range(score_df.shape[0])]

In [31]:
stu

['stu_0',
 'stu_1',
 'stu_2',
 'stu_3',
 'stu_4',
 'stu_5',
 'stu_6',
 'stu_7',
 'stu_8',
 'stu_9']

In [32]:
data.index = stu

In [33]:
data

语文  数学  英语  政治  体育
stu_0  61  80  87  53  42
stu_1  56  80  62  84  74
stu_2  78  44  66  71  67
stu_3  77  47  41  89  80
stu_4  42  62  96  63  63
stu_5  70  54  67  56  48
stu_6  44  62  49  45  91
stu_7  58  96  92  46  89
stu_8  97  95  48  42  92
stu_9  53  42  76  82  61

In [34]:
# data.index[2] = "tongxue"

In [35]:
data.reset_index()

index  语文  数学  英语  政治  体育
0  stu_0  61  80  87  53  42
1  stu_1  56  80  62  84  74
2  stu_2  78  44  66  71  67
3  stu_3  77  47  41  89  80
4  stu_4  42  62  96  63  63
5  stu_5  70  54  67  56  48
6  stu_6  44  62  49  45  91
7  stu_7  58  96  92  46  89
8  stu_8  97  95  48  42  92
9  stu_9  53  42  76  82  61

In [36]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  61  80  87  53  42
1  56  80  62  84  74
2  78  44  66  71  67
3  77  47  41  89  80
4  42  62  96  63  63
5  70  54  67  56  48
6  44  62  49  45  91
7  58  96  92  46  89
8  97  95  48  42  92
9  53  42  76  82  61

In [37]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
'year': [2012, 2014, 2013, 2014],
'sale':[55, 40, 84, 31]})

In [38]:
df

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [39]:
df.set_index("year")

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [43]:
df = df.set_index(["year","month"])

# 3 MutiIndex与Panel
## 3.1 MutiIndex

In [44]:
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

In [45]:
df.index

MultiIndex([(2012,  1),
            (2014,  4),
            (2013,  7),
            (2014, 10)],
           names=['year', 'month'])

In [46]:
df.index.names

FrozenList(['year', 'month'])

In [47]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [48]:
arrays = [[1,2,1,2],["r","b","r","b"]]
pd.MultiIndex.from_arrays(arrays,names=("num","col"))

MultiIndex([(1, 'r'),
            (2, 'b'),
            (1, 'r'),
            (2, 'b')],
           names=['num', 'col'])

## 3.2 panel

In [53]:
p = pd.Panel(data=np.arange(24).reshape(4,3,2),
items=list('ABCD'),
major_axis=pd.date_range('20130101', periods=3),
minor_axis=['first', 'second'])

<ipython-input-53-daf59da11ead>:1: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  p = pd.Panel(data=np.arange(24).reshape(4,3,2),


TypeError: Panel() takes no arguments